iisidro-postgresql:
  container_name: iisidro-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/iisidro/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=iisidro
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
